# Generated by Django 3.2.7 on 2021-09-08 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='details',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='subject',
            new_name='title',
        ),
    ]
